#!/bin/sh

# Script to generate simple directory based binary name structure.

genname(){
	withext="`echo $i  | sed 's#../exec/##' | sed 's#/#_#g' \
		               | sed 's#._exec_##'`"
	withoutext="${withext%.*}"
	echo "$withoutext"
}

. $SHMODS/chores/scriptdir.sh
rdir="`scriptdir`"
cd "$rdir"

bins=`for i in ./exec/* ; do
	find $i -executable -type f #| sed 's#_\.#/#'
done`

for i in $bins ; do
	echo $i
	echo `readlink -f $i `
	ln -vsf "`readlink -f $i`" "$BIN/`genname \"$i\"`"
done
