#!/bin/sh

# Script to generate simple directory based binary name structure.

genname(){
	withext="`echo $i | sed 's#../exec/##' | sed 's#/#_#g'`"
	withoutext="${withext%.*}"
	echo "$withoutext"
}

. $SHMODS/chores/scriptdir.sh
rdir="`scriptdir`"
cd "$rdir"

bins=`for i in ./exec/* ; do
	find $i -executable -type f | sed 's#./#../#'
done`

for i in $bins ; do
	ln -vsf "$i" ./bin/"`genname \"$i\"`"
done
